### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by juhkarhu** [HoolaBoola/tsoha_article_library#1]
After cloning the project and following the installation instructions the front page loads as expected. After clicking to register a new user (btw: it says login in the registration page button) the app displays 'Internal Server Error' message (Pastebin of the printed bash log here: https://pastebin.com/kQMSubyi). The same problem is in the heroku app version as well unfortunately. 

Although I couldn't get very far with the app, I took a look at the code. All of the code is in a single file. I recommend that you divide the code into logical parts (for example SQL into one file and route-handling to other. It's worth the effort since it makes it easier to make changes as you don't have to scroll endless lines of code. HTML-templates look fine. SQL-schema creation clause looks quite complicated, is there any way to simplify it? 

The idea for this app sounds absolutely great and I would have loved to test the working app and it's features. Even if the peer-review targets change, I'm gonna take a look at this one again. Keep it up!

**Comment by HoolaBoola** [comment]
Ah, the server error came from a last-minute addition ("ROM" instead of "FROM" in an SQL query...)
The error is now fixed, should work once more.

I haven't really had the energy to focus on this project due to personal issues lately, but all of the mentioned points are on my to-do list :)

> SQL-schema creation clause looks quite complicated, is there any way to simplify it?

Yes, the current one is simply a dump from postgresql, but it should be trivial to strip the unnecessary stuff.
